// TODO: write macro that convert enum to union
pub trait Phenotype {
    type Value;
    type Discriminant;
    fn discriminant(&self) -> Self::Discriminant;
    // Return autogenerated enum
    fn value(self) -> Option<Self::Value>;
    fn invert_discriminant(tag: Self::Discriminant, value: Self::Value) -> Self;
}
