// TODO: write macro that convert enum to union
pub trait Phenotype {
    type Value;
    fn discriminant(&self) -> usize;
    // Return autogenerated enum
    fn value(&self) -> Option<Self::Value>;
}