// TODO: write macro that convert enum to union
pub trait Phenotype {
    const NUM_VARIANTS: usize;
    type Value;
    fn discriminant(&self) -> usize;
    // Return autogenerated enum
    fn value(self) -> (usize, Option<Self::Value>);
    fn invert_discriminant(tag: usize, value: Self::Value) -> Self;
}
